Adding sign in page
Maxgioman/Restavratsia pull request #9
Opened 2020-03-28 14:53 UTC by AVorobel

Added sign in page, css styles, images, routing to sign in page nad back to main page + jsconfig.json with absolute path import config

2020-03-28 14:54 UTC, AVorobel commented
![](https://github.trello.services/images/mini-trello-icon.png) [sign in sign up page](https://trello.com/c/WU218jrO/7-sign-in-sign-up-page)

2020-03-30 10:29 UTC, SmolenskiyK requested changes

2020-03-30 10:29 UTC, SmolenskiyK commented on .idea/RestavratsiaRepos.iml
> +<?xml version="1.0" encoding="UTF-8"?>
please add ```.idea/``` to .gitignore

2020-03-30 10:29 UTC, SmolenskiyK commented on restavratsia/src/components/SignIn.js
> +import {
Потрібно відокремити логіку роутінгу від самої пейджи.

2020-03-30 10:29 UTC, SmolenskiyK commented on restavratsia/src/components/SignIn.js
> +import './css-styles/dynamic-styles.css';
думаю краще юзати препроцесори css

2020-03-30 10:31 UTC, SmolenskiyK commented on restavratsia/src/components/SignIn.js
> +    Link
потрібно відокремити логіку роутінгу від самохї пейджи

2020-04-03 13:41 UTC, Maxgioman reviewed
Хороша робота, не знайшов тут траблів

2020-04-03 13:41 UTC, Maxgioman approved these changes

2020-04-03 14:10 UTC, MykhayloMuzyka approved these changes

2020-04-03 14:14 UTC, merged